# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Proficiency Exercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Proficiency Exercise
pod 'SDWebImage'
  target 'Proficiency ExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Proficiency ExerciseUITests' do
    # Pods for testing
  end

end
